analysis/urls.py
from django.urls import path
from . import views
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

app_name = "analysis"
#try:
urlpatterns = [
    path('upload/', views.FileFieldView.as_view(), name='upload'),
    path(
        'create-meta-report/', 
         views.CreateMetaReport.as_view(),
         name='create_meta_report'
    ),
    path(
        'meta-reports/',
         views.MetaReportListView.as_view(),
         name='metareport_list'
    ),
    path(
        'meta-reports/<int:pk>/',
        views.MetaReportDetailView.as_view(),
        name='meta_report_detail'
    ),
    path(
        'create-report/',
        views.CreateWellReport.as_view(),
        name='create_report'
    ),
    path(
        'enter-well-data/',
        views.CreateWellReading.as_view(),
        name='enter_well_data'
    ),
    path(
        'reports/',
        views.WellReportListView.as_view(),
        name='report_list'
    ),
    path(
        'reports/<int:pk>/',
        views.WellReportDetailView.as_view(),
        name='report_detail'
    )
]
#except:
#    urlpatterns = []

wells/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views, settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

#try:
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(),  name='home'), 
    path('accounts/', include('accounts.urls')),
    path('analysis/', include('analysis.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#except:
#    urlpatterns = []

analysis/models.py
# analysis/models.py
from datetime import datetime
from django.conf import settings
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.contrib import messages
from django.urls import reverse
from io import TextIOWrapper, BytesIO
from matplotlib import pyplot as plt
from pytz import timezone as ptz
import os
import csv
import numpy as np
import pandas as pd
# Create your models here.


class Unit(models.Model):
    name = models.CharField(max_length=256, default="unit")
    measurement_type = models.CharField(max_length=256, default=None)
    
    def __str__(self):
        return self.name

class Well(models.Model):
    name = models.CharField(max_length=256, default=None)
    location = models.CharField(max_length=256, default=None)

    def __str__(self):
        return self.name

class WellReport(models.Model):
    well = models.ForeignKey(Well, on_delete=models.CASCADE)
    title = models.CharField(max_length=256, default='untitled')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    creation_date = models.DateTimeField(default=timezone.now)
    start_date = models.DateTimeField(default=timezone.now)
    end_date = models.DateTimeField(default=timezone.now)
    graph = models.ImageField(upload_to='reports/%Y/%m/%d/', default=None)
    unit = models.ForeignKey(Unit, on_delete=models.CASCADE)
    mean = models.FloatField(default=None)
    minimum= models.FloatField(default=None)
    maximum = models.FloatField(default=None)
    first = models.FloatField(default=None)
    first_date = models.DateTimeField(null=True)
    last = models.FloatField(default=None)
    last_date = models.DateTimeField(null=True)
    total_readings = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('analysis:report_detail',
            args=[str(self.id)]
        )

    def make_double_sma_time_fig(
        self,
        df,
        units='units',
        sma1=20,
        sma2=60,
        title='Untitled',
        total_values=0,
        ):
        '''
        A helper function to make a time series graph with two moving averages.
    
        Keyword Arguments:
        df -- a data frame object
        units -- a string to be used to label the y axis
        sma1 -- the number of periods for the first moving average
        sma2 -- the number of periods for the second moving average
        title -- the title of the graph
        total_values -- the total amount of values; used to determine
            whether or not to display moving averages
        '''
    
    
        plt.plot(df, label=units)
        if total_values >= sma1:
            plt.plot(
                df.rolling(
                    sma1,
                    min_periods=1,
                    center=True
                ).mean(),
                label='{} value SMA'.format(sma1)
            )
        if total_values >= sma2:
            plt.plot(
                df.rolling(
                    sma2,
                    min_periods=1,
                    center=True
                ).mean(),
                label='{} value SMA'.format(sma2)
            )
        plt.hlines(df.mean(), df.index[0], df.index[-1], linestyle='--', label='mean')
        plt.xlabel("Date")
        plt.ylabel(units)
        plt.title(title)
        plt.legend()
        plt.tick_params(axis='x', rotation=45)
        plt.tight_layout()
        return plt

    def analyze_by_date(self, request, form):
        '''
        Takes a POST request and form object containing data that will be used for
        creating WellReport objects.
        Looks for the following keys in form.cleaned_data:
        wells - a list of choices from MultipleModelChoice form field
        units - a list of choices from a MultipleModelChoice form field
        start_date - an entry from a DateTimeField form field
        end_date - an entry from a DateTimeField form field
        '''
        dt_format = "%x" # Set datetime format here
        # Get the wells specified in the form data
        wells = form.cleaned_data['wells']
        units = form.cleaned_data['units']
        start_date = form.cleaned_data['start_date']
        end_date = form.cleaned_data['end_date']
        # Perform the analysis for each well
        for well in wells:
            #print(type(well))
            w = Well.objects.get(name=well)
            #print(w)
            for unit in units:
                u = Unit.objects.get(name=unit)
                # Match well readings match the well
                # and fall within the date range
                # and match the unit
                matched_readings = WellReading.objects.filter(
                    well=w,
                    date__range=(start_date, end_date),
                    unit=u
                )
                # Alert the user
                if not matched_readings:
                    messages.info(
                        request,
                        '{}, {} : No readings were matched between {} and {}.'.format(
                            well,
                            unit,
                            start_date.strftime(dt_format),
                            end_date.strftime(dt_format),
                        )
                    )

                # Prepare date for MatPlot and NumPy
                values = []
                dates = []
                mr_count = matched_readings.count() - 1
                try:
                    first_date = matched_readings.earliest('date').date
                except:
                    pass
                try:
                    last_date = matched_readings.latest('date').date
                except:
                    pass
                for reading in matched_readings:
                    values.append(reading.value)
                    dates.append(reading.date.strftime(dt_format))
                if len(values) == len(dates):
                    #for i in range(len(values)):
                    #    print('{} :{}'.format(values[i], dates[i]))
                    pass
                else:
                    print("number of values does not match number of dates")
                # Get the statistics
                if values:
                    mean = np.mean(values)
                    minimum = min(values)
                    maximum = max(values)
                    first = values[0]
                    last = values[-1]
                    total_readings = len(values)
                    # Create a WellReport model instance for each file
                    report_title='{} {} in {}'.format(
                        w,
                        u.measurement_type.title(),
                        u.name,
                        first_date.strftime(dt_format),
                        last_date.strftime(dt_format)
                    )
                    report, created = self.objects.get_or_create(
                        well=w,
                        user=request.user,
                        title=report_title + ' from {} to {}'.format(
                            first_date.strftime(dt_format),
                            last_date.strftime(dt_format)
                        ),
                        start_date=start_date,
                        end_date=end_date,
                        unit=u,
                        mean=mean,
                        minimum=minimum,
                        maximum=maximum,
                        first=first,
                        first_date=first_date,
                        last=last,
                        last_date=last_date,
                        total_readings=total_readings,
                    )
                    # Create the graph
                    # Create the path where the graph will live
                    dti = pd.DatetimeIndex(dates)
                    df = pd.Series(values, index=dti)
                    # Sort the dataframe bay date
                    df = df.sort_index()
                    print(dti.freq)
    
                    dest_dir = os.path.join(
                        settings.BASE_DIR,
                        datetime.now().strftime("media/%Y/%m/%d/")
                    )
                    try:
                        os.makedirs(dest_dir)
                    except:
                        pass
    
                    dest_path = dest_dir+str(report.pk)+".png"
    
                    plt = self.make_double_sma_time_fig(
                        self, 
                        df, 
                        u.name, 
                        20, 
                        60, 
                        report_title, 
                        total_readings
                    )
                    plt.savefig(dest_path)
                    plt.close()
    
                    if report:
                        report.graph = datetime.now().strftime(
                            "media/%Y/%m/%d/"
                        )+str(report.pk)+".png"
                        report.save()
                else:
                    print('There was no data for {}'.format(w))

class MetaReport(models.Model):
    title = models.CharField(max_length=256, default='untitled')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    creation_date = models.DateTimeField(default=timezone.now)
    start_date = models.DateTimeField(default=timezone.now)
    end_date = models.DateTimeField(default=timezone.now)
    csv = models.FileField(upload_to='reports/%Y/%m/%d/', default=None)
    
    def __str__(self):
        return '{} - {}'.format(
            self.start_date.strftime("%x"), 
            self.end_date.strftime("%x"),
        )

    def export_csv(self, request, form):
        '''
        Takes a POST request and form object containing data that will be used for
        creating a MetaReport containing a CSV file.

analysis/forms.py
from django import forms
from . import models

#class DocumentForm(ModelForm):
#    class Meta:
#        model = models.Document
#        fields = ('upload_name', 'description', 'document',)


class UploadFileForm(forms.Form):
    file_field = forms.FileField(
        widget=forms.ClearableFileInput(attrs={
            'multiple': True,
        }),
        label="",
    )
    file_field.widget.attrs.update({'class': 'btn-dark'})

class MetaReportSelector(forms.Form):
    start_date = forms.DateTimeField()
    end_date = forms.DateTimeField()
    units = forms.ModelMultipleChoiceField(
        queryset=models.Unit.objects.all(),
        widget=forms.CheckboxSelectMultiple(), 
        required=True
    )

class DateRangeSelector(forms.Form):
    wells = forms.ModelMultipleChoiceField(
        queryset=models.Well.objects.all(),
        widget=forms.CheckboxSelectMultiple(), 
        required=True
    )
    start_date = forms.DateTimeField()
    end_date = forms.DateTimeField()
    units = forms.ModelMultipleChoiceField(
        queryset=models.Unit.objects.all(),
        widget=forms.CheckboxSelectMultiple(), 
        required=True
    )

analysis/views.py
# analysis/views.py
from datetime import datetime
from pytz import timezone
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.mixins import(
    LoginRequiredMixin,
    PermissionRequiredMixin,
    )
from django.views.generic.edit import CreateView
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic.edit import FormView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.core.files.images import ImageFile
from matplotlib import pyplot as plt
from .forms import UploadFileForm, DateRangeSelector, MetaReportSelector
from .models import Well, WellReading, WellReport, Unit, MetaReport
from io import TextIOWrapper, BytesIO 
import os
import csv
import numpy as np
import pandas as pd

pd.plotting.register_matplotlib_converters()
# Create your views here.

class FileFieldView(LoginRequiredMixin, FormView):
    # View for the mulitple file upload form
    # Allows a user to upload csv files to be converted to django models
    form_class = UploadFileForm
    template_name = 'analysis/upload.html'
    success_url = reverse_lazy('analysis:upload')

    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        files = request.FILES.getlist('file_field')
        if form.is_valid():
            for f in files:
                try:
                    wr = WellReading
                    wr.handle_csv_file(wr, request, f, f.name)
                except:
                    messages.error(
                        request,
                        '{} could not be read'.format(
                            f.name
                        )
                    )
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

class CreateMetaReport(LoginRequiredMixin, FormView):
    # View to create a report based on a date range
    form_class = MetaReportSelector
    template_name = 'analysis/createmetareport.html'
    success_url = reverse_lazy('analysis:metareport_list')

    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        if form.is_valid():
            mr = MetaReport
            mr.export_csv(mr, request, form)
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

class MetaReportListView(LoginRequiredMixin, ListView):
    model = MetaReport
    paginate_by = 100
    ordering = ['-creation_date']
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

class MetaReportDetailView(LoginRequiredMixin, DetailView):
    model = MetaReport
    template_name = 'analysis/metareport_detail.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

class CreateWellReport(LoginRequiredMixin, FormView):
    # View to create a report based on a date range
    form_class = DateRangeSelector
    template_name = 'analysis/createwellreport.html'
    success_url = reverse_lazy('analysis:report_list')

    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        if form.is_valid():
            wr = WellReport
            wr.analyze_by_date(wr, request, form)
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

class WellReportListView(LoginRequiredMixin, ListView):
    model = WellReport
    paginate_by = 100
    ordering = ['-creation_date']
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

class WellReportDetailView(LoginRequiredMixin, DetailView):
    model = WellReport
    template_name = 'analysis/wellreport_detail.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

class CreateWellReading(LoginRequiredMixin, CreateView):
    model = WellReading
    template_name = 'analysis/wellreading_create_form.html'
    fields = [
        'well',
        'date',
        'value',
        'unit',
        'tag_comments',
    ]
    
    def get_success_url(self):
        return reverse_lazy('analysis:enter_well_data') 

analysis/templates/analysis/createmetareport.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body_block %}
<h3>Choose a range of dates to analyze</h3>
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {% bootstrap_form form %}
  <input type="submit" value="Analyze" class="btn btn-default">
</form>
{% if messages %}
<h3><i>Errors:</i></h3>
<pre>
  {% for message in messages %}
    {{ message }}
  {% endfor %}
</pre>
{% endif %}
{% endblock %}

analysis/templates/analysis/createwellreport.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body_block %}
<h3>Choose a range of dates to analyze</h3>
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {% bootstrap_form form %}
  <input type="submit" value="Analyze" class="btn btn-default">
</form>
{% endblock %}

analysis/templates/analysis/metareport_detail.html
{% extends 'base.html' %}
{% block body_block %}
<div class="container">
  <div class="container">
    <h3>{{ object.title }}</h3>
  </div>
  <div class="container">
    <a href="{{ object.csv.url }}" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Download CSV</a>
    <p><i>This meta report was created by {{ object.user }} on {{ object.creation_date }}.</i></p>
  </div>
</div>  
{% endblock %}

analysis/templates/analysis/metareport_list.html
{% extends 'base.html' %}
{% block body_block %}
<div class="container">
  <div class="jumbotron">
    <h1>Meta Reports</h1>
  </div>
  <div class="container">
    <p>Click <a href="{% url 'analysis:create_meta_report' %}">here</a> to create a meta report.</p>
    {% if object_list %}
      <ul class="list-group">
        {% for meta_report in object_list %}
          <li class="list-group-item"><a href="{% url 'analysis:meta_report_detail' meta_report.pk %}">{{ meta_report.title }}</a></li>
        {% endfor %}
      </ul>
    {% else %}
    <p>There are no meta reports yet.</p>
    {% endif %}
  </div>  
{% endblock %}

analysis/templates/analysis/upload.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body_block %}
<div class="container-fluid">
  <div class="container jumbotron">
    <h3>Import Raw CSV Data</h3>
  </div>
  <div class="container">
  <div class="row">
  <div class="col-sm-auto">
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {% bootstrap_form form %}
      <input type="submit" value="Import" class="btn btn-primary">
    </form>
  </div> 
  </div>
  <br>
  <hr>
  <div class="row">
  <div class="col-md-auto">
    <h4>CSV format requirements</h4>
    <br>
    <ul class="list-group">
      <li class="list-group-item">
        <p>The columns must follow the following header:</p>
        <table class="table table-bordered">
          <thead>
            <th>A</th><th>B</th><th>C</th><th>D</th><th>E</th><th>F</th><th>G</th><th>H</th>
          </thead>
          <tbody>
            <tr>
              <td>Date/Time</td><td>Date</td><td>Time</td><td>Value</td><td>Quality Code</td><td>Interploation Type</td><td>Empty</td><td>tagComments</td>
            </tr>
          </tbody>
        </table>
      </li>
      <li class="list-group-item">
        <p>The csv files must use a comma as the delimiter.</p>
        <p>Example:</p>
        <div class="container precode">
           <pre>08/16/2012 12:00:00,08/16/2012,12:00:00,-12.08,1135,101</pre>
        </div> 		
      </li>
      <li class="list-group-item">The first row will not be read so please make sure your files contain a header as the first row</li>
   </ul> 
  </div>
  </div>
  </div>
{% endblock %}

analysis/templates/analysis/wellreading_create_form.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body_block %}
<h3>Enter new well data</h3>
<form method="post">
  {% csrf_token %}
  {% bootstrap_form form %}
  <input type="submit" value="Enter" class="btn btn-default">
</form>
{% endblock %}

analysis/templates/analysis/wellreport_detail.html
{% extends 'base.html' %}
{% block body_block %}
<div class="container">
  <div class="container">
    <h3>{{ object.title }}</h3>
  </div>
  <div class="container">
    <img src="/{{ object.graph }}"><br>
    <p>Mean: {{ object.mean|floatformat:-2 }} {{ object.unit }}</p>
    <p>Minumum: {{ object.minimum }} {{ object.unit }}</p>
    <p>Maximium: {{ object.maximum }} {{ object.unit }}</p>
    <p>First Reading: {{ object.first }} {{ object.unit }} on {{ object.first_date|date:"m/d/y" }}</p>
    <p>Last Reading: {{ object.last }} {{ object.unit }} on {{ object.last_date|date:"m/d/y" }}</p> 
    <p>Total Readings: {{ object.total_readings }}</p> 
    <p><i>This report was created by {{ object.user }} on {{ object.creation_date }}.</i></p>
  </div>
</div>  
{% endblock %}

analysis/templates/analysis/wellreport_list.html
{% extends 'base.html' %}
{% block body_block %}
<div class="container">
  <div class="jumbotron">
    <h1>Well Reports</h1>
  </div>
  <div class="container">
    <p>Click <a href="{% url 'analysis:create_report' %}">here</a> to create reports</p>
    {% if object_list %}
      <ul class="list-group">
        {% for wellreport in object_list %}
          <li class="list-group-item"><a href="{{ wellreport.get_absolute_url }}">{{ wellreport.title }}</a></li>
        {% endfor %}
      </ul>
    {% else %}
    <p>There are no reports yet.</p>
    {% endif %}
  </div>  
{% endblock %}