accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "accounts"

urlpatterns = [
    path(
        "login/", 
        auth_views.LoginView.as_view(template_name="accounts/login.html"),
        name="login",
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(),
        name="logout",
    ),
    path(
        "signup/",
        views.RegisterUser.as_view(),
        name="signup",
    ),
]

analysis/urls.py
from django.urls import path
from . import views
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

app_name = "analysis"
#try:
urlpatterns = [
    path('upload/', views.FileFieldView.as_view(), name='upload'),
    path(
        'create-meta-report/', 
         views.CreateMetaReport.as_view(),
         name='create_meta_report'
    ),
    path(
        'meta-reports/',
         views.MetaReportListView.as_view(),
         name='metareport_list'
    ),
    path(
        'meta-reports/<int:pk>/',
        views.MetaReportDetailView.as_view(),
        name='meta_report_detail'
    ),
    path(
        'create-report/',
        views.CreateWellReport.as_view(),
        name='create_report'
    ),
    path(
        'enter-well-data/',
        views.CreateWellReading.as_view(),
        name='enter_well_data'
    ),
    path(
        'reports/',
        views.WellReportListView.as_view(),
        name='report_list'
    ),
    path(
        'reports/<int:pk>/',
        views.WellReportDetailView.as_view(),
        name='report_detail'
    )
]
#except:
#    urlpatterns = []

wells/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views, settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

#try:
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(),  name='home'), 
    path('accounts/', include('accounts.urls')),
    path('analysis/', include('analysis.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#except:
#    urlpatterns = []

templates/base.html
<!DOCTYPE html>

<html lang="en">
<head>
  <meta charset="utf-8">

  <title>Well Data Analysis</title>
  <meta name="description" content="">
  <meta name="author" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">  
</head>

<body>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="nav-item navbar-brand" href="{% url 'home' %}">Well Data Analysis</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'analysis:enter_well_data' %}">Enter Data</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'analysis:upload' %}">Import Data</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'analysis:report_list' %}">Reports</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'analysis:metareport_list' %}">Meta Reports</a>
          </li>
          {% if user.is_staff %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
            </li>
          {% endif %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:login' %}">Login</a> 
          </li>
        {% endif %}
      </ul>
    </div>
  </nav>
  {% if messages %}
    <div class="jumbotron">
      <p class="lead">INFORMATION:</p>
      <pre>
        {% for message in messages %}
          {{ message }}
        {% endfor %}
      </pre>
    </div>
  {% endif %}
  <div class="container">
    {% block body_block %}
    <!-- Anything outside of this will be inhereited if you extend! -->
    {% endblock %}
  </div>
</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block body_block %}
{% if user.is_authenticated %}
  <div class="container">
    <div class="jumbotron">
      <h3>Well Data Analysis</h3>
    </div>
    <div class="container card-columns">
      <div class="card" style="width: 18rem;">
        <!--<img src="{% static "enter_keyboard_computer_keys_technology_internet_business_office-935315.jpg" %}" class="card-img-top" alt="keyboard">-->
        <div class="card-body">
          <h5 class="card-title">Enter New Data</h5>
          <p class="card-text">Enter new readings for existing wells in the database.</p>
          <a href="{% url 'analysis:enter_well_data' %}" class="btn btn-primary">Enter Data</a>
        </div>
      </div>
      <div class="card" style="width: 18rem;">
        <!--<img src="{% static "floppy-disk-27223_960_720.png" %}" class="card-img-top" alt="disk import">-->
        <div class="card-body">
          <h5 class="card-title">Import Raw Data</h5>
          <p class="card-text">Use the custom import feature to populate data by uploading one or more CSV files.</p>
          <a href="{% url 'analysis:upload' %}" class="btn btn-primary">Import</a>
        </div>
      </div>
      <div class="card" style="width: 18rem;">
        <!--<img src="{% static "2d14aca81666a470a529694a66c8-1455413.jpg" %}" class="card-img-top" alt="making a report">-->
        <div class="card-body">
          <h5 class="card-title">View Well Reports</h5>
          <p class="card-text">See a list of all data reports that have been generated.</p>
          <a href="{% url 'analysis:report_list' %}" class="btn btn-primary">View Reports</a>
        </div>
      </div>
      <div class="card" style="width: 18rem;">
        <!--<img src="{% static "accountancy_bookkeeping_accounting_bookkeeper_calculator_investment_report_audit-1041551.jpg" %}" class="card-img-top" alt="calculator"> -->
        <div class="card-body">
          <h5 class="card-title">Create Reports</h5>
          <p class="card-text">Generate multiple reports within a specified time range.</p>
          <a href="{% url 'analysis:create_report' %}" class="btn btn-primary">Create</a>
        </div>
      </div>
      <div class="card" style="width: 18rem;">
        <!--<img src="{% static "floppy-disk-27223_960_720.png" %}" class="card-img-top" alt="disk import">-->
        <div class="card-body">
          <h5 class="card-title">Export Meta Report</h5>
          <p class="card-text">Export an analysis report in CSV format</p>
          <a href="{% url 'analysis:create_meta_report' %}" class="btn btn-primary">Export</a>
        </div>
      </div>
    </div>
  </div>
  <div class="container">
    <p>To add new wells and metric types you must either create them via the import feature or use the <a href="admin">admin</a>.</p>
  </div>
{% else %}
<div class="container">
  <div class="jumbotron">
<h1>Welcome, please log in</h1>
  </div>
</div>
{% endif %}
{% endblock %}